services:
  paper:
    image: itzg/minecraft-server
    restart: always
    tty: true
    stdin_open: true
    ports:
      - 25567:25567
      - 8804:8804 # Plan
      - 8100:8100 # Bluemap
    environment:
      - TZ=Asia/Tokyo
      - EULA=TRUE
      - VERSION=1.20.4
      - TYPE=PAPER
      - OPS=m1sk9,Colk_
      # note: https://docker-minecraft-server.readthedocs.io/en/latest/configuration/jvm-options/
      - MEMORY=1G
    volumes:
      - ./data:/data
